name: review-needed
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Review required
        run: echo "This pull request or push to main requires review."
