name: review-needed-learning-github-actions
on: 
  pull_request:
    branches:
      - main 
  push: 
    branches:
      - main

jobs: 
  check_review:
    runs-on: ubuntu-latest
    steps: 
      - name: Check bats version
        run: npm install -g bats
      - name: Check review
        uses: actions/checkout@v3
        run: echo "Review needed for this pull request"