name: Review-needed-before-deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Request review
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.G__TOKEN }}
          reviewers: tan911 
          assignees: tan911 
          title: 'Please review and approve before deployment'
          body: 'Please review and approve this pull request before it can be deployed to production.'
      - name: Wait for approval
        id: approval
        uses: github-script@v4
        with:
          github-token: ${{ secrets.G__TOKEN }}
          script: |
            const { data } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            return { approvals: data.reviews.filter(review => review.state === 'APPROVED').length }
      - name: Check approvals
        run: |
          if [ $(( $(echo ${{ steps.approval.outputs.approvals }}) )) -lt 1 ]; then
            echo "Not enough approvals. Cancelling deployment."
            exit 1
          fi

  deploy:
    needs: review
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL__TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL__PROJECT__ID }}



# name: Review-needed-before-deployment

# on:
#   pull_request:
#     branches:
#       - main
#   push:
#     branches:
#       - main

# jobs:
#   review:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Request review
#         uses: peter-evans/create-pull-request-review@v5
#         with:
#           github-token: ${{ secrets.G__TOKEN }}
#           reviewers: tan911 
#           assignees: tan911 
#           approve: false
#           comment: Please review and approve before deployment
#       - name: Wait for approval
#         uses: andymckay/wait-for-approval@v1
#         with:
#           github-token: ${{ secrets.G__TOKEN }}
#           wait-for-approvals: true

#   deploy:
#     needs: review
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy to Vercel
#         uses: amondnet/vercel-action@v20.0.0
#         with:
#           vercel-token: ${{ secrets.VERCEL__TOKEN }}
#           vercel-project-id: ${{ secrets.VERCEL__PROJECT__ID }}

